language: generic

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main"
              key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - powershell
#    - os: osx
#      osx_image: xcode9.1
#      before_install:
#        - brew tap caskroom/cask
#        - brew cask install powershell
  fast_finish: true

install:
  - pwsh -File "${env:TRAVIS_BUILD_DIR}/tests/Install.ps1"

before_script:
  - pwsh -File "${env:TRAVIS_BUILD_DIR}/tests/Build.ps1"

script:
  - pwsh -File "${env:TRAVIS_BUILD_DIR}/tests/Main.Tests.ps1"

after_success:
#  - pwsh -File "${env:TRAVIS_BUILD_DIR}/deploy.ps1"
